name: Django CI/CD  # More descriptive name

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          python manage.py test

  deploy:  # New deploy job
    needs: build  # Only run deploy if build job is successful
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on pushes to main
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3 #Use the action for heroku deployment
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} #Get the api key from the secrets
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} #Get the app name from the secrets
          heroku_email: ${{ secrets.HEROKU_EMAIL }} #Get the email from the secrets
